In [1]:
import numpy as np
import torch
from scipy.signal import convolve

# 创建两个简单的信号
signal1 = np.array([1, 2, 3])
signal2 = np.array([4, 5])

# 执行卷积
result = convolve(signal1, signal2,mode = 'same')

print(result)

[ 4 13 22]


In [1]:
max_disparity=50

In [4]:
cost = np.ones(max_disparity+1)

In [5]:
cost

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
cost[0:2]

array([1., 1.])

In [7]:
 label = torch.eye(2).cuda()[[1]*len([1,2,3,1,5])]

In [8]:
label

tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]], device='cuda:0')